### ISSUE TITLE
如何强制性停止运行的程序？

### ISSUE THREAD

**Issue by Is-Sakura-i** [dataabc/weibo-search#11]
您好，我用命令行cmd执行的程序，但是在按关键词搜的时候发现自己关键词弄错了，然后这个关键词的数据特别多，原来以为关掉换个关键词再运行就可以了，，没想到再运行还是会根据上次的关键词接着运行……请问怎么强制性停止这个关键词的搜索啊？

**Comment by dataabc** [comment]
删除crawls文件夹重新运行就好。

readme中运行程序的命令可以让程序接着上次的执行，会生成一个保存上次进度的文件夹crawls，删除它就能重新执行。

**Comment by Is-Sakura-i** [comment]
好的！可以了！谢谢嗷。
现在有个问题还想请教您一下，就是我现在用的python3.7的环境，win10，在weibo-spider下面执行命令scrapy crawl search -s JOBDIR=crawls/search，然后报了下面的错：
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\scrapy.exe\__main__.py", line 5, in <module>
  File "d:\anaconda3\lib\site-packages\scrapy\__init__.py", line 34, in <module>
    from scrapy.spiders import Spider
  File "d:\anaconda3\lib\site-packages\scrapy\spiders\__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "d:\anaconda3\lib\site-packages\scrapy\http\__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "d:\anaconda3\lib\site-packages\scrapy\http\request\form.py", line 10, in <module>
    import lxml.html
  File "d:\anaconda3\lib\site-packages\lxml\html\__init__.py", line 53, in <module>
    from .. import etree
ImportError: DLL load failed: 找不到指定的模块。
请问这是为什么呀？我在其他文件夹下面也试过，还是报这个错。

**Comment by dataabc** [comment]
感谢反馈。

可以参考<https://my.oschina.net/u/3900854/blog/3059710>

**Comment by Is-Sakura-i** [comment]
试了好久……还是不行，，，上次我记得是直接pip install scrapy就好了，这次就一直报这个错，害，请问一下这个是因为少了哪个包吗？

**Comment by Is-Sakura-i** [comment]
补充一下，我在anaconda prompt中运行import scrapy和import lxml等都没有报错，为什么用cmd就不可以呀？

**Comment by dataabc** [comment]
可能是lxml的问题。

参考<https://bbs.csdn.net/topics/392202545>看看能不能解决

**Comment by Is-Sakura-i** [comment]
用了这些都不可以555，，，想请问一下：在pycharm中我是用的虚拟环境python3.5，本身我的anaconda中的python是3.7版本的，然后用cmd运行这个程序报的错发现一直是在本来的那个3.7的环境中，这是为什么呀？是不是它依赖的只能是本身的环境，跟我的虚拟环境无关？

**Comment by dataabc** [comment]
在cmd中不使用虚拟环境就和虚拟环境无关，否则jiu 有关系。

你应该是在cmd中直接执行scrapy crawl search -s JOBDIR=crawls/search，如果这样只和本身环境有关。不知道你直接在cmd中输入python3,然后import lxml，是否有错。

**Comment by Is-Sakura-i** [comment]
啊啊啊啊啊啊弄好了！是的，刚开始我以为只要在pycharm中更改解释器就好了，cmd直接执行的，一直弄不了……虽然不知道为什么在本身的环境中一直执行不了，重新创了个3.5的也不可以，后来又弄了个3.6版本的，在cmd中激活3.6版本的虚拟环境，然后再运行竟然可以了！不知道是不是版本的原因，，
还有就是，我在本身的那个环境cmd中输入python,然后import lxml，是没有任何错误的，，，
超级感谢您！
