### ISSUE TITLE
【已解决】运行scrapy crawl search -s JOBDIR=crawls/search报错 Unhandled error in Deferred: ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by Yangyehong** [dataabc/weibo-search#115]
Unhandled error in Deferred:
2021-11-07 09:42:39 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "d:\software\anaconda3\lib\site-packages\scrapy\crawler.py", line 192, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "d:\software\anaconda3\lib\site-packages\scrapy\crawler.py", line 196, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "d:\software\anaconda3\lib\site-packages\twisted\internet\defer.py", line 1909, in unwindGenerator
    return _cancellableInlineCallbacks(gen)  # type: ignore[unreachable]
  File "d:\software\anaconda3\lib\site-packages\twisted\internet\defer.py", line 1816, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status)
--- <exception caught here> ---
  File "d:\software\anaconda3\lib\site-packages\twisted\internet\defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "d:\software\anaconda3\lib\site-packages\scrapy\crawler.py", line 89, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
builtins.ImportError: DLL load failed: 找不到指定的模块。

2021-11-07 09:42:39 [twisted] CRITICAL:
Traceback (most recent call last):
  File "d:\software\anaconda3\lib\site-packages\twisted\internet\defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "d:\software\anaconda3\lib\site-packages\scrapy\crawler.py", line 89, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
ImportError: DLL load failed: 找不到指定的模块。

**Comment by cloudy-sfu** [comment]
你报错的位置都在scrapy函数库内部，应该是和脚本没关系的，建议尝试重新安装scrapy函数库。

**Comment by Yangyehong** [comment]
> 你报错的位置都在scrapy函数库内部，应该是和脚本没关系的，建议尝试重新安装scrapy函数库。

我在cmd里卸载重新安装了好几次。我是要在anaconda里重新安装吗，那个很慢，我就没在那里边装

**Comment by cloudy-sfu** [comment]
理论上不需要在anaconda里重新安装。我的版本也是2.5.1，版本方面应该没问题。

**Comment by Yangyehong** [comment]
> 理论上不需要在anaconda里重新安装。我的版本也是2.5.1，版本方面应该没问题。

应该是settings的设置有问题，目前还没找到哪里出错了

**Comment by Yangyehong** [comment]
我的anaconda里少了两个文件。
解决方法见：https://blog.csdn.net/qinqigang/article/details/91410465
