### ISSUE TITLE
无修改代码运行出错typeerror

### ISSUE THREAD

**Issue by minacy** [dataabc/weibo-search#118]
2021-11-13 16:18:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=***> (referer: None)
Traceback (most recent call last):
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/utils/python.py", line 353, in __next__
    return next(self.data)
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/utils/python.py", line 353, in __next__
    return next(self.data)
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/xiao/weibo/venv/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "/home/xiao/weibo/weibo-search/weibo/spiders/search.py", line 107, in parse
    for weibo in self.parse_weibo(response):
  File "/home/xiao/weibo/weibo-search/weibo/spiders/search.py", line 426, in parse_weibo
    attitudes_count = re.findall(r'\d+.*', attitudes_count)
  File "/usr/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object

想知道这是什么原因呀

**Comment by minacy** [comment]
找到原因，在点赞数为0时网页不显示数字，这时attitudes_count为空，加一个if判断就好

**Comment by dataabc** [comment]
感谢反馈，已经修复了，再次感谢。
