### ISSUE TITLE
运行报错，求大佬指点！

### ISSUE THREAD

**Issue by haoran10101** [dataabc/weibo-search#130]
E:\weibo-search-master>scrapy crawl search
Traceback (most recent call last):
  File "e:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\Scripts\scrapy.exe\__main__.py", line 4, in <module>
  File "e:\anaconda\lib\site-packages\scrapy\cmdline.py", line 9, in <module>
    from scrapy.crawler import CrawlerProcess
  File "e:\anaconda\lib\site-packages\scrapy\crawler.py", line 18, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "e:\anaconda\lib\site-packages\scrapy\core\engine.py", line 14, in <module>
    from scrapy.core.scraper import Scraper
  File "e:\anaconda\lib\site-packages\scrapy\core\scraper.py", line 16, in <module>
    from scrapy.utils.log import failure_to_exc_info, logformatter_adapter
  File "e:\anaconda\lib\site-packages\scrapy\utils\log.py", line 12, in <module>
    from scrapy.utils.versions import scrapy_components_versions
  File "e:\anaconda\lib\site-packages\scrapy\utils\versions.py", line 12, in <module>
    from scrapy.utils.ssl import get_openssl_version
  File "e:\anaconda\lib\site-packages\scrapy\utils\ssl.py", line 1, in <module>
    import OpenSSL
  File "e:\anaconda\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "e:\anaconda\lib\site-packages\OpenSSL\crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "e:\anaconda\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "e:\anaconda\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: 找不到指定的程序。

**Comment by cloudy-sfu** [comment]
cryptodome, cryptodomex, crypto 大概有几个名字差不多的, 我记得Windows不支持其中一两个的, 请你查一下兼容性. 另外DLL load failed也有可能是文件被篡改了, 可以考虑重装函数库:
```
pip uninstall cryptography
pip install cryptography
```
