### ISSUE TITLE
网络中断过一次，程序报错，请问这个时什么问题呀！

### ISSUE THREAD

**Issue by qq910523230** [dataabc/weibo-search#136]
2021-12-12 16:47:07 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "d:\python\lib\site-packages\scrapy\commands\crawl.py", line 27, in run
    self.crawler_process.start()
  File "d:\python\lib\site-packages\scrapy\crawler.py", line 327, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "d:\python\lib\site-packages\twisted\internet\base.py", line 1318, in run
    self.mainLoop()
  File "d:\python\lib\site-packages\twisted\internet\base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "d:\python\lib\site-packages\twisted\internet\base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "d:\python\lib\site-packages\scrapy\utils\reactor.py", line 50, in __call__
    return self._func(*self._a, **self._kw)
  File "d:\python\lib\site-packages\scrapy\core\engine.py", line 124, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "d:\python\lib\site-packages\scrapy\core\engine.py", line 153, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "d:\python\lib\site-packages\scrapy\core\scheduler.py", line 95, in next_request
    request = self._dqpop()
  File "d:\python\lib\site-packages\scrapy\core\scheduler.py", line 129, in _dqpop
    return self.dqs.pop()
  File "d:\python\lib\site-packages\scrapy\pqueues.py", line 94, in pop
    m = q.pop()
  File "d:\python\lib\site-packages\scrapy\squeues.py", line 61, in pop
    request = super().pop()
  File "d:\python\lib\site-packages\scrapy\squeues.py", line 37, in pop
    s = super().pop()
  File "d:\python\lib\site-packages\queuelib\queue.py", line 228, in pop
    self.f.seek(-size - self.SIZE_SIZE, os.SEEK_END)
builtins.OSError: [Errno 22] Invalid argument

**Comment by dataabc** [comment]
感谢反馈。应该是进度没有保存好，删除crawls内的search文件夹，重新运行。如果还有问题，欢迎继续讨论。
