### ISSUE TITLE
用scrapy crawl search运行出错

### ISSUE THREAD

**Issue by lieol** [dataabc/weibo-search#14]
代码提示
Scrapy 2.1.0 - no active project

Unknown command: crawl

Use "scrapy" to see available commands

**Comment by lieol** [comment]
网上说在scrapy.cfg所在目录运行就可以，但是具体怎么实现？

**Comment by dataabc** [comment]
cd 到weibo-search目录，然后运行scrapy crawl search就可以

**Comment by lieol** [comment]
Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python35-32\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python35-32\lib\site-packages\scrapy\cmdline.py", line 112, in execute
    settings = get_project_settings()
  File "c:\program files (x86)\python35-32\lib\site-packages\scrapy\utils\project.py", line 69, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "c:\program files (x86)\python35-32\lib\site-packages\scrapy\settings\__init__.py", line 287, in setmodule
    module = import_module(module)
  File "c:\program files (x86)\python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\weibo\weibo\settings.py", line 15
    ITEM_PIPELINES = {
                 ^
SyntaxError: invalid syntax

**Comment by lieol** [comment]
可以运行了，但是又有新的错误

**Comment by dataabc** [comment]
说明setting.py的第15行有格式错误，比如多了个逗号等，修改下就可以

**Comment by modun** [comment]
python pip 默认设置成ptyhon3可以正常运行；
python pip 默认的python2并和python3并存时，不能运行，有遇到的吗？求教下，谢谢！

**Comment by modun** [comment]
> python pip 默认设置成ptyhon3可以正常运行；
> python pip 默认的python2并和python3并存时，不能运行，有遇到的吗？求教下，谢谢！

已解决，通过以下命令：

python3 -m scrapy crawl search -s JOBDIR=crawls/search
