### ISSUE TITLE
关于 No module named 'weibo.utils' 问题

### ISSUE THREAD

**Issue by ShaoqingH** [dataabc/weibo-search#18]
大神你好，感谢您的代码，有个问题不知道怎么解决，恳请您帮助。
我用sublime运行search的时候，出现了下面的错误：
Traceback (most recent call last):
  File "/Users/hanshaoqing/Downloads/weibo-search-master/weibo/spiders/search.py", line 10, in <module>
    import weibo.utils.util as util
ModuleNotFoundError: No module named 'weibo.utils'; 'weibo' is not a package
[Finished in 0.6s with exit code 1]
[cmd: ['/Library/Frameworks/Python.framework/Versions/3.7/bin/python3', '-u', '/Users/hanshaoqing/Downloads/weibo-search-master/weibo/spiders/search.py']]
[dir: /Users/hanshaoqing/Downloads/weibo-search-master/weibo/spiders]
[path: /Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/anaconda3/bin:/Users/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin]

这个是什么原因啊？怎么解决？

**Comment by dataabc** [comment]
感谢反馈。

出错是因为直接运行的py文件，应该在eibo-search文件夹下运行
```
scrapy crawl search -s JOBDIR=crawls/search
```
如果还有问题欢迎继续讨论。

**Comment by ShaoqingH** [comment]
感谢您，没想到您能这么快回复。我刚开始接触这个，因为想抓取一个话题下的帖子做个研究，但是技术上确实还不太行。我这样试了一下，不知道操作上是否有问题？但提示了下面的错误：

可能我的问题有些低级，耽误您的宝贵时间，但我自己来回检索确实费了不少劲，也没解决。主要是没有系统的学习python，基础不太好。
所以还请您见谅。感谢您！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月20日(星期六) 下午4:48
收件人:&nbsp;"dataabc/weibo-search"<weibo-search@noreply.github.com&gt;;
抄送:&nbsp;"1197818137"<1197818137@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weibo-search] 关于 No module named 'weibo.utils' 问题 (#18)





 
感谢反馈。
 
出错是因为直接运行的py文件，应该在eibo-search文件夹下运行
 scrapy crawl search -s JOBDIR=crawls/search  
如果还有问题欢迎继续讨论。

**Comment by dataabc** [comment]
客气了。

你上面说“我这样试了一下，不知道操作上是否有问题？但提示了下面的错误：”，但是下面是空行，没有错误，不知道是又出现了错误还是指上面的错误？现在能正确运行了吗？

**Comment by ShaoqingH** [comment]
刚才插入的图片，可能没看到，我复制了一下在终端的提示，不知道是否方便您查看（附件里我加上了截图）：
(base) hanshaoqingdeMacBook-Pro:weibo-search-master hanshaoqing$ scrapy crawl search -s JOBDIR=crawls/search
Traceback (most recent call last):
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/bin/scrapy", line 8, in <module&gt;
&nbsp; &nbsp; sys.exit(execute())
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapy/cmdline.py", line 112, in execute
&nbsp; &nbsp; settings = get_project_settings()
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapy/utils/project.py", line 69, in get_project_settings
&nbsp; &nbsp; settings.setmodule(settings_module_path, priority='project')
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapy/settings/__init__.py", line 287, in setmodule
&nbsp; &nbsp; module = import_module(module)
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
&nbsp; &nbsp; return _bootstrap._gcd_import(name[level:], package, level)
&nbsp; File "<frozen importlib._bootstrap&gt;", line 1006, in _gcd_import
&nbsp; File "<frozen importlib._bootstrap&gt;", line 983, in _find_and_load
&nbsp; File "<frozen importlib._bootstrap&gt;", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'weibo.settings'; 'weibo' is not a package
(base) hanshaoqingdeMacBook-Pro:weibo-search-master hanshaoqing$ scrapy crawl search
Traceback (most recent call last):
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/bin/scrapy", line 8, in <module&gt;
&nbsp; &nbsp; sys.exit(execute())
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapy/cmdline.py", line 112, in execute
&nbsp; &nbsp; settings = get_project_settings()
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapy/utils/project.py", line 69, in get_project_settings
&nbsp; &nbsp; settings.setmodule(settings_module_path, priority='project')
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapy/settings/__init__.py", line 287, in setmodule
&nbsp; &nbsp; module = import_module(module)
&nbsp; File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
&nbsp; &nbsp; return _bootstrap._gcd_import(name[level:], package, level)
&nbsp; File "<frozen importlib._bootstrap&gt;", line 1006, in _gcd_import
&nbsp; File "<frozen importlib._bootstrap&gt;", line 983, in _find_and_load
&nbsp; File "<frozen importlib._bootstrap&gt;", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'weibo.settings'; 'weibo' is not a package

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Lei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月20日(星期六) 下午5:34
收件人:&nbsp;"dataabc/weibo-search"<weibo-search@noreply.github.com&gt;;
抄送:&nbsp;"1197818137"<1197818137@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dataabc/weibo-search] 关于 No module named 'weibo.utils' 问题 (#18)





 
客气了。
 
你上面说“我这样试了一下，不知道操作上是否有问题？但提示了下面的错误：”，但是下面是空行，没有错误，不知道是又出现了错误还是指上面的错误？现在能正确运行了吗？

**Comment by dataabc** [comment]
我怀疑是scrapy版本问题，可以参考#2，貌似是同一个问题，按照最后帖子的方法应该可以解决。

**Comment by jiaqij0623** [comment]
> 感谢反馈。
> 
> 出错是因为直接运行的py文件，应该在eibo-search文件夹下运行
> 
> ```
> scrapy crawl search -s JOBDIR=crawls/search
> ```
> 
> 如果还有问题欢迎继续讨论。

请问输入此代码后显示syntax error，应该如何改正？

**Comment by dataabc** [comment]
@jiaqij0623 一般是语法错误，可能是你修改代码导致的，看看有没有详细提示信息。
