### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CharlesTeng-li** [dataabc/weibo-search#213]
D:\网络舆情软件\weibo-search-master\weibo-search-master>scrapy crawl search
2022-05-17 17:30:13 [scrapy.core.scraper] ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=%E9%95%BF%E6%B2%99%20%E6%88%BF%20%E5%80%92%E5%A1%8C&typeall=1&suball=1&timescope=custom:2022-04-29-0:2022-05-09-0&display=0&retcode=6102> (referer: None)
Traceback (most recent call last):
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\utils\defer.py", line 132, in iter_errback
    yield next(it)
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\utils\python.py", line 354, in __next__
    return next(self.data)
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\utils\python.py", line 354, in __next__
    return next(self.data)
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\19763\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "D:\网络舆情软件\weibo-search-master\weibo-search-master\weibo\spiders\search.py", line 106, in parse
    for weibo in self.parse_weibo(response):
  File "D:\网络舆情软件\weibo-search-master\weibo-search-master\weibo\spiders\search.py", line 461, in parse_weibo
    retweet['id'] = retweet_sel[0].xpath(
TypeError: 'NoneType' object is not subscriptable

**Comment by dataabc** [comment]
是不是没有修改cookie？
