### ISSUE TITLE
无法爬取信息，远程端无响应

### ISSUE THREAD

**Issue by lqz19980404** [dataabc/weibo-search#220]
2022-06-01 21:15:31 [scrapy.core.scraper] ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=%E8%BF%AA%E4%B8%BD%E7%83%AD%E5%B7%B4&scope=ori&suball=1&timescope=custom:2020-03-01-0:2020-03-02-0> (referer: None)
Traceback (most recent call last):
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\xxx\anaconda3\envs\py372\lib\site-packages\scrapy\core\spidermw.py", line 56, in _evaluate_iterable
    for r in iterable:
  File "C:\lqz2\wb\主要工具\关键词爬取\xin\weibo-search-master\weibo-search-master\weibo\spiders\search.py", line 107, in parse
    for weibo in self.parse_weibo(response):
  File "C:\lqz2\wb\主要工具\关键词爬取\xin\weibo-search-master\weibo-search-master\weibo\spiders\search.py", line 425, in parse_weibo
    attitudes_count = re.findall(r'\d+.*', attitudes_count)
  File "C:\Users\xxx\anaconda3\envs\py372\lib\re.py", line 225, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
 这是什么问题啊

**Comment by dataabc** [comment]
是最新版本吗？

**Comment by lqz19980404** [comment]
是最新版 按照之前的操作以及解决了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2022年6月1日(星期三) 晚上10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dataabc/weibo-search] 无法爬取信息，远程端无响应 (Issue #220)





 
是最新版本吗？

**Comment by Yangkuishiny** [comment]
> 是最新版 按照之前的操作以及解决了，谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Chen ***@***.***&gt;; 发送时间: 2022年6月1日(星期三) 晚上10:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [dataabc/weibo-search] 无法爬取信息，远程端无响应 (Issue #220) 是最新版本吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，这是什么问题啊，怎么解决的，我也遇到了同样的问题
