### ISSUE TITLE
报编码错误的问题

### ISSUE THREAD

**Issue by Huangjunlin** [dataabc/weibo-search#23]
麻烦请教一下，执行scrapy crawl search -s JOBDIR=crawls/search 命令后，报“UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)” 错误的问题

**Comment by dataabc** [comment]
感谢反馈。

这是编码错误，能否贴出详细出错信息及搜索关键词，方便调试，感谢。

**Comment by Huangjunlin** [comment]
2020-07-22 18:54:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=PMPM&typeall=1&suball=1&timescope=custom:2020-06-01-0:2020-07-23-0> (referer: None)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/lib/python2.7/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/lib/python2.7/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/lib/python2.7/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/lib/python2.7/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/www/weibo-search/weibo/spiders/search.py", line 99, in parse
    for weibo in self.parse_weibo(response):
  File "/www/weibo-search/weibo/spiders/search.py", line 386, in parse_weibo
    weibo['article_url'] = self.get_article_url(txt_sel)
  File "/www/weibo-search/weibo/spiders/search.py", line 285, in get_article_url
    if text.startswith('发布了头条文章'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

**Comment by dataabc** [comment]
修改search.py文件的285行，将
```
if text.startswith('发布了头条文章'):
```
改为
```
if text.startswith(u'发布了头条文章'):
```

**Comment by Huangjunlin** [comment]
感谢大大，上面的问题已经解决了。但是又报了一个新的问题
2020-07-23 13:50:13 [scrapy.core.scraper] ERROR: Error downloading <GET https://s.weibo.com/weibo?q=PMPM&typeall=1&suball=1&timescope=custom:2020-06-01-0:2020-07-23-0>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib64/python2.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 982, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
DNSLookupError: DNS lookup failed: no results for hostname lookup: s.weibo.com.


尝试了网上的一些方法，说是 Robot协议 的影响，修改setting.py文件，增加 ROBOTSTXT_OBEY = False。还是没效果。

**Comment by dataabc** [comment]
感谢反馈，我没有复现错误。怀疑是scrapy版本问题，我的是scrapy2.0，你可以升级到最新的官方版本或者更换其它版本
