### ISSUE TITLE
作者你好，运行您的代码出错，没有任何结果，可以请教您一下吗

### ISSUE THREAD

**Issue by Yangkuishiny** [dataabc/weibo-search#230]
2022-06-25 22:05:29 [scrapy.core.scraper] ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=%E6%95%B0%E6%8D%AE%E6%B5%81%E9%80%9A&scope=ori&suball=1&timescope=custom:2022-06-01-0:2022-06-06-0> (referer: None)
Traceback (most recent call last):
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/utils/defer.py", line 132, in iter_errback
    yield next(it)
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/utils/python.py", line 354, in __next__
    return next(self.data)
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/utils/python.py", line 354, in __next__
    return next(self.data)
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/spidermiddlewares/referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/spidermiddlewares/urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/song/anaconda3/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "/home/song/下载/weibo-search/weibo/spiders/search.py", line 107, in parse
    for weibo in self.parse_weibo(response):
  File "/home/song/下载/weibo-search/weibo/spiders/search.py", line 425, in parse_weibo
    attitudes_count = re.findall(r'\d+.*', attitudes_count)
  File "/home/song/anaconda3/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object

**Comment by Yangkuishiny** [comment]
我解决了，翻了之前的问题，找到了解决办法，直接scrapy crawl search就可以了

**Comment by 1933211129** [comment]
和题主一样的问题 两个月前使用过没有问题 现在出现和题主一样的问题 直接scrapy crawl search报错和题主一样

**Comment by 1933211129** [comment]
已解决！！更新一下cookie！
