### ISSUE TITLE
ModuleNotFoundError: No module named 'weibo.settings'; 'weibo' is not a package

### ISSUE THREAD

**Issue by emilygong-zhuying** [dataabc/weibo-search#243]
您好，我看了之前几个一样的问题，但是我两个路径下面都已经有__init__.py了，所以我不是很确定为什么会报错。然后我看了#2，但是我不是很明白我需要做些什么，是创建一个virtual environment吗？多谢！
<img width="724" alt="Screen Shot 2022-07-12 at 9 39 02 PM" src="https://user-images.githubusercontent.com/74880355/178651882-25a3d2d3-50d1-4bbf-848c-98613ea54ac8.png">
。

**Comment by emilygong-zhuying** [comment]
我之前去了scrapy和pillow的官网按照他们给的command安装的，所以版本也应该都是最新的，但是还是不行。然后我看scrapy说建议建一个单独的venv，所以我尝试在venv里面pip install scrapy和pillow，但是还是同样的问题。也尝试了重新clone github repo... 不知道您有没有什么别的建议，谢谢！
<img width="827" alt="Screen Shot 2022-07-13 at 12 12 21 PM" src="https://user-images.githubusercontent.com/74880355/178813249-05c27829-12a5-4c2d-ad72-6f3192c5a9b9.png">

**Comment by dataabc** [comment]
我看 #2 可能就是版本没安装正确，只想到这个原因。

**Comment by abby9999** [comment]
我也有这个问题，请问解决了吗

**Comment by emilygong-zhuying** [comment]
> 我也有这个问题，请问解决了吗

我在我的电脑上没有解决，但是用别人的就可以。估计是我电脑里的什么dependency的问题。

**Comment by wyycommu** [comment]
不好意思时隔小半年打扰楼主，我也想问一下，目前可行的解决方法还是换一台电脑吗

**Comment by XiaonaHe** [comment]
w我也遇到了这个问题，大家解决了吗？C:\Users\hexiaona>cd C:\weibo_master

C:\weibo_master>scrapy crawl search -s JOBDIR=crawls/search
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Scripts\scrapy-script.py", line 10, in <module>
    sys.exit(execute())
             ^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\scrapy\cmdline.py", line 125, in execute
    settings = get_project_settings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\scrapy\utils\project.py", line 71, in get_project_settings
    settings.setmodule(settings_module_path, priority="project")
  File "C:\ProgramData\anaconda3\Lib\site-packages\scrapy\settings\__init__.py", line 316, in setmodule
    module = import_module(module)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1135, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'weibo.settings'; 'weibo' is not a package

**Comment by XiaonaHe** [comment]
> w我也遇到了这个问题，大家解决了吗？C:\Users\hexiaona>cd C:\weibo_master
> 
> C:\weibo_master>scrapy crawl search -s JOBDIR=crawls/search 回溯（最近一次调用最后一次）： 文件“C:\ProgramData\anaconda3\Scripts\scrapy-script.py”，第 10 行，在 sys.exit(execute())中 ^^^^^^^^^ 文件“C:\ProgramData\anaconda3\Lib\site-packages\scrapy\cmdline.py”，第 125 行，在 execute settings = get_project_settings()中 ^^^^^^^^^^^^^^^^^^^^^^^^ 文件“C:\ProgramData\anaconda3\Lib\site-packages\scrapy\utils\project.py”，第 71 行，在 get_project_settings 中 settings.setmodule(settings_module_path, priority="project") 文件“C:\ProgramData\anaconda3\Lib\site-packages\scrapy\settings_ _init_ _.py”，第 316 行，在 setmodule 中 module = import_module(module) ^^^^^^^^^^^^^^^^^^^^^^^^ 文件“C:\ProgramData\anaconda3\Lib\importlib_ _init_ _.py”，第 126 行，位于 import_module 中 return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 文件“”，第 1204 行，位于 _gcd_import 中 文件“”，第 1176 行，位于 _find_and_load 中 文件“”，第 1135 行，位于 _find_and_load_unlocked 中 ModuleNotFoundError：没有名为“weibo.settings”的模块；“weibo”不是包

把所有的包都卸载了，然后问题解决了，猜可能是之前安装了weibo这个包 重名了
