### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zuoluoyake** [dataabc/weibo-search#244]
请问作者这个怎么办呀
D:\微博爬虫\weibo-search-master>scrapy crawl search -s JOBDIR=crawls/search
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "D:\Python\lib\site-packages\scrapy\cmdline.py", line 144, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "D:\Python\lib\site-packages\scrapy\crawler.py", line 290, in __init__
    super().__init__(settings)
  File "D:\Python\lib\site-packages\scrapy\crawler.py", line 167, in __init__
    self.spider_loader = self._get_spider_loader(settings)
  File "D:\Python\lib\site-packages\scrapy\crawler.py", line 161, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "D:\Python\lib\site-packages\scrapy\spiderloader.py", line 67, in from_settings
    return cls(settings)
  File "D:\Python\lib\site-packages\scrapy\spiderloader.py", line 24, in __init__
    self._load_all_spiders()
  File "D:\Python\lib\site-packages\scrapy\spiderloader.py", line 51, in _load_all_spiders
    for module in walk_modules(name):
  File "D:\Python\lib\site-packages\scrapy\utils\misc.py", line 88, in walk_modules
    submod = import_module(fullpath)
  File "D:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\微博爬虫\weibo-search-master\weibo\spiders\search.py", line 205
    else:
    ^^^^
SyntaxError: invalid syntax

**Comment by dataabc** [comment]
是不是修改代码了？是格式错误，定位到了search.py的205行，具体错误有说明。

**Comment by zuoluoyake** [comment]
非常感谢，那里就是看到第66个提问里关于重复爬取的问题，看到您写了修改里面一个函数，我就也修改了一下，我改回来试一试，这么晚打扰您啦

**Comment by zuoluoyake** [comment]
成功啦，成功啦，非常感谢您！

**Comment by philsmos** [comment]
> 成功啦，成功啦，非常感谢您！

你好，请问最终是怎么解决的呢，我也出现这问题了

**Comment by zuoluoyake** [comment]
> > 成功啦，成功啦，非常感谢您！
> 
> 你好，请问最终是怎么解决的呢，我也出现这问题了

就是在第66个提问关于重复爬取的问题里，作者给出了一段search.py的修改代码，我就在作者现在版本的代码里也进行了修改，但修改之后就出现了这个问题，改回去没事了
