### ISSUE TITLE
为什么会提示AttributeError: 'NoneType' object has no attribute 'split'这个啊

### ISSUE THREAD

**Issue by Kinggggggggggggggg** [dataabc/weibo-search#309]
D:\weibo\text\weibo-search-master>scrapy crawl search -s JOBDIR=crawls/search
2022-12-16 22:42:13 [scrapy.core.scraper] ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=%E4%BA%8C%E5%8D%81%E5%9B%9B%E8%8A%82%E6%B0%94&scope=ori&suball=1&timescope=custom:2022-02-04-0:2022-02-06-0> (referer: None)
Traceback (most recent call last):
  File "D:\PYTHON\lib\site-packages\scrapy\utils\defer.py", line 240, in iter_errback
    yield next(it)
  File "D:\PYTHON\lib\site-packages\scrapy\utils\python.py", line 338, in __next__
    return next(self.data)
  File "D:\PYTHON\lib\site-packages\scrapy\utils\python.py", line 338, in __next__
    return next(self.data)
  File "D:\PYTHON\lib\site-packages\scrapy\core\spidermw.py", line 79, in process_sync
    for r in iterable:
  File "D:\PYTHON\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\PYTHON\lib\site-packages\scrapy\core\spidermw.py", line 79, in process_sync
    for r in iterable:
  File "D:\PYTHON\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 336, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "D:\PYTHON\lib\site-packages\scrapy\core\spidermw.py", line 79, in process_sync
    for r in iterable:
  File "D:\PYTHON\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "D:\PYTHON\lib\site-packages\scrapy\core\spidermw.py", line 79, in process_sync
    for r in iterable:
  File "D:\PYTHON\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 32, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "D:\PYTHON\lib\site-packages\scrapy\core\spidermw.py", line 79, in process_sync
    for r in iterable:
  File "D:\weibo\text\weibo-search-master\weibo\spiders\search.py", line 107, in parse
    for weibo in self.parse_weibo(response):
  File "D:\weibo\text\weibo-search-master\weibo\spiders\search.py", line 358, in parse_weibo
    ).split('/')[-1].split('?')[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by dataabc** [comment]
可能是之前速度太快暂时被限制了，限制一段时间自动解除。

**Comment by Kinggggggggggggggg** [comment]
> 可能是之前速度太快暂时被限制了，限制一段时间自动解除。

那怎呢弄啊   是过一段时间后它自己就好了 还是需要其他的啊（感谢您的回复~~~）

**Comment by dataabc** [comment]
如果确实是被限制，一般情况下，一段时间它自己就好了，不需要其他。

**Comment by Sphinxxx233** [comment]
> > 可能是之前速度太快暂时被限制了，限制一段时间自动解除。
> 
> 那怎呢弄啊 是过一段时间后它自己就好了 还是需要其他的啊（感谢您的回复~~~）

想问一下一段时间是多久，我好像也是这个报错 = =

**Comment by lili4569** [comment]
> > 可能是之前速度太快暂时被限制了，限制一段时间自动解除。
> 
> 那怎呢弄啊 是过一段时间后它自己就好了 还是需要其他的啊（感谢您的回复~~~）

请问您现在解决了吗？目前我也是这里报错

**Comment by Kinggggggggggggggg** [comment]
我最近没用了 暂时不知道还是不是这个情况&nbsp; 我抽时间再去看看吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月4日(周六) 凌晨0:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dataabc/weibo-search] 为什么会提示AttributeError: 'NoneType' object has no attribute 'split'这个啊 (Issue #309)




   
可能是之前速度太快暂时被限制了，限制一段时间自动解除。
  
那怎呢弄啊 是过一段时间后它自己就好了 还是需要其他的啊（感谢您的回复~~~）
  
请问您现在解决了吗？目前我也是这里报错
