### ISSUE TITLE
报错ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=%E8%BF%AA%E4%B8%BD%E7%83%AD%E5%B7%B4&scope=ori&suball=1&timescope=custom:2022-01-01-0:2022-03-02-0>

### ISSUE THREAD

**Issue by Sphinxxx233** [dataabc/weibo-search#312]
运行scrapy crawl search -s JOBDIR=crawls/search出现了以下报错
ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=%E8%BF%AA%E4%B8%BD%E7%83%AD%E5%B7%B4&scope=ori&suball=1&timescope=custom:2022-01-01-0:2022-03-02-0> (referer: None)
Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 132, in iter_errback
    yield next(it)
  File "E:\anaconda3\lib\site-packages\scrapy\utils\python.py", line 354, in __next__
    return next(self.data)
  File "E:\anaconda3\lib\site-packages\scrapy\utils\python.py", line 354, in __next__
    return next(self.data)
  File "E:\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "E:\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "E:\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "E:\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "E:\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "E:\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "E:\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "E:\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "E:\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 66, in _evaluate_iterable
    for r in iterable:
  File "D:\weibo-search-master\weibo-search-master\weibo\spiders\search.py", line 107, in parse
    for weibo in self.parse_weibo(response):
  File "D:\weibo-search-master\weibo-search-master\weibo\spiders\search.py", line 356, in parse_weibo
    weibo['bid'] = sel.xpath(
AttributeError: 'NoneType' object has no attribute 'split'

想问一下怎么解决

**Comment by dataabc** [comment]
可能是之前速度太快被限制了，限制在一段时间后会自动解除。

**Comment by fansoloma** [comment]
请问您解决了吗，需要多少时间啊，我也是这个报错

**Comment by zxmd2001** [comment]
我也是一样的错误

**Comment by chengchen-z** [comment]
请问解决了吗，我也是这个问题，不知道如何处理

**Comment by DarianLX** [comment]
出现了同样问题，亟待解决
