### ISSUE TITLE
报错了显示ParamSpec' from 'typing_extensions'，我安装了好几个版本都不行，请问有解决办法吗，谢谢

### ISSUE THREAD

**Issue by stonecropa** [dataabc/weibo-search#347]
PS E:\Googledownload\weibo-search-master> scrapy crawl search -s JOBDIR=crawls/search
Traceback (most recent call last):
  File "D:\conda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\conda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\conda\Scripts\scrapy.exe\__main__.py", line 4, in <module>
  File "D:\conda\lib\site-packages\scrapy\__init__.py", line 12, in <module>
    from scrapy.http import FormRequest, Request
  File "D:\conda\lib\site-packages\scrapy\http\__init__.py", line 10, in <module>
    from scrapy.http.request.form import FormRequest
  File "D:\conda\lib\site-packages\scrapy\http\request\form.py", line 16, in <module>
    from scrapy.http.response.text import TextResponse
  File "D:\conda\lib\site-packages\scrapy\http\response\text.py", line 26, in <module>
    from scrapy.utils.response import get_base_url
  File "D:\conda\lib\site-packages\scrapy\utils\response.py", line 12, in <module>
    from twisted.web import http
  File "D:\conda\lib\site-packages\twisted\web\http.py", line 122, in <module>
    from twisted.internet import address, interfaces, protocol
  File "D:\conda\lib\site-packages\twisted\internet\protocol.py", line 18, in <module>
    from twisted.internet import defer, error, interfaces
  File "D:\conda\lib\site-packages\twisted\internet\defer.py", line 42, in <module>
    from typing_extensions import Literal, ParamSpec, Protocol
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (D:\conda\lib\site-packages\typing_extensions.py)

**Comment by aqibufu** [comment]
我是更新一下 typing_extensions 的版本就好了
`pip install -U typing_extensions `
