### ISSUE TITLE
 报错 unconverted data remains

### ISSUE THREAD

**Issue by zhuzhu8811** [dataabc/weibo-search#362]
Traceback (most recent call last):
  File "D:\anoconda\envs\python36\lib\runpy.py", line 193, in _run_module_as_main            
    "__main__", mod_spec)                                                                    
  File "D:\anoconda\envs\python36\lib\runpy.py", line 85, in _run_code                       
    exec(code, run_globals)                                                                  
  File "D:\anoconda\envs\python36\Scripts\scrapy.exe\__main__.py", line 7, in <module>       
  File "D:\anoconda\envs\python36\lib\site-packages\scrapy\cmdline.py", line 153, in execute 
    cmd.crawler_process = CrawlerProcess(settings)                                           
  File "D:\anoconda\envs\python36\lib\site-packages\scrapy\crawler.py", line 289, in __init__
    super().__init__(settings)                                                               
  File "D:\anoconda\envs\python36\lib\site-packages\scrapy\crawler.py", line 166, in __init__
    self.spider_loader = self._get_spider_loader(settings)                                   
  File "D:\anoconda\envs\python36\lib\site-packages\scrapy\crawler.py", line 160, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "D:\anoconda\envs\python36\lib\site-packages\scrapy\spiderloader.py", line 67, in from_settings
    return cls(settings)
  File "D:\anoconda\envs\python36\lib\site-packages\scrapy\spiderloader.py", line 24, in __init__
    self._load_all_spiders()
  File "D:\anoconda\envs\python36\lib\site-packages\scrapy\spiderloader.py", line 51, in _load_all_spiders
    for module in walk_modules(name):
  File "D:\anoconda\envs\python36\lib\site-packages\scrapy\utils\misc.py", line 88, in walk_modules
    submod = import_module(fullpath)
  File "D:\anoconda\envs\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\毕业设计\weibo-search-master\weibo\spiders\search.py", line 15, in <module>
    class SearchSpider(scrapy.Spider):
  File "E:\毕业设计\weibo-search-master\weibo\spiders\search.py", line 37, in SearchSpider
    if util.str_to_time(start_date) > util.str_to_time(end_date):
  File "E:\毕业设计\weibo-search-master\weibo\utils\util.py", line 105, in str_to_time
    result = datetime.strptime(text, '%Y-%m-%d')
  File "D:\anoconda\envs\python36\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "D:\anoconda\envs\python36\lib\_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:

**Comment by dataabc** [comment]
好像是时间转换格式问题，你打开util.py，看看str_to_time的text内容是什么，我现在不方便调试，不确定是不是时间格式变了。
