### ISSUE TITLE
爬取4小时后爬不动并出现struct.error

### ISSUE THREAD

**Issue by pxaklbe** [dataabc/weibo-search#364]
开发者您好，我在爬取数据4小时后发现程序terminal端自动停止，于是用control+c保存断点再爬，但开始遇到各种错误，现在遇到的是Unhandled Error 
Traceback (most recent call last):
  File "/Users/cindys/enter/lib/python3.9/site-packages/scrapy/commands/crawl.py", line 31, in run
    self.crawler_process.start()
  File "/Users/cindys/enter/lib/python3.9/site-packages/scrapy/crawler.py", line 383, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/Users/cindys/enter/lib/python3.9/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
后面还有好几行，最后跟着struct.error: unpack requires a buffer of 4 bytes。请问怎样解决呢？

**Comment by pxaklbe** [comment]
谢谢，我再试试！

**Comment by pxaklbe** [comment]
> 可能进度没保存好，我也不确定。如果是进度原因，只能删除进度文件。建议删除前备份进度文件

大神您好，我又试了一下。设置的随机爬取一天，200多个关键词，希望每个词爬取100多条。但总在几个小时后程序就自动停止，终端显示：(base) surfer-172-29-11-81-hotspot:weibo-search-master S$。请问您知道这个出现的原因是什么吗？有什么解决思路呢？

**Comment by dataabc** [comment]
这个我也不知道，可能是爬多了微博的限制吧，实在不行你分成几组关键词，分开爬。

**Comment by pxaklbe** [comment]
> 这个我也不知道，可能是爬多了微博的限制吧，实在不行你分成几组关键词，分开爬。

开发者大神您好，所以正常情况下，程序是支持每个关键词在某一天爬取100条的对吗？

**Comment by dataabc** [comment]
这个您需要自己修改search.py代码。
