### ISSUE TITLE
博主你好请教您个问题，ValueError: day is out of range for month

### ISSUE THREAD

**Issue by liwenhi** [dataabc/weibo-search#380]
PS F:\weibo-search-master\weibo> scrapy crawl search -s JOBDIR=crawls/search
Traceback (most recent call last):
  File "F:\software\python3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\software\python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\software\python3.7\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "F:\software\python3.7\lib\site-packages\scrapy\cmdline.py", line 157, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "F:\software\python3.7\lib\site-packages\scrapy\crawler.py", line 325, in __init__
    super().__init__(settings)
  File "F:\software\python3.7\lib\site-packages\scrapy\crawler.py", line 197, in __init__
    self.spider_loader = self._get_spider_loader(settings)
  File "F:\software\python3.7\lib\site-packages\scrapy\crawler.py", line 191, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "F:\software\python3.7\lib\site-packages\scrapy\spiderloader.py", line 69, in from_settings
    return cls(settings)
  File "F:\software\python3.7\lib\site-packages\scrapy\spiderloader.py", line 24, in __init__
    self._load_all_spiders()
  File "F:\software\python3.7\lib\site-packages\scrapy\spiderloader.py", line 53, in _load_all_spiders
    for module in walk_modules(name):
  File "F:\software\python3.7\lib\site-packages\scrapy\utils\misc.py", line 92, in walk_modules
    submod = import_module(fullpath)
  File "F:\software\python3.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\weibo-search-master\weibo\spiders\search.py", line 15, in <module>
    class SearchSpider(scrapy.Spider):
  File "F:\weibo-search-master\weibo\spiders\search.py", line 37, in SearchSpider
    if util.str_to_time(start_date) > util.str_to_time(end_date):
  File "F:\weibo-search-master\weibo\utils\util.py", line 105, in str_to_time
    result = datetime.strptime(text, '%Y-%m-%d')
  File "F:\software\python3.7\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "F:\software\python3.7\lib\_strptime.py", line 544, in _strptime
    datetime_date(year, 1, 1).toordinal() + 1
ValueError: day is out of range for month
PS F:\weibo-search-master\weibo> scrapy crawl search -s JOBDIR=crawls/search
Traceback (most recent call last):
  File "F:\software\python3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\software\python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\software\python3.7\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "F:\software\python3.7\lib\site-packages\scrapy\cmdline.py", line 157, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "F:\software\python3.7\lib\site-packages\scrapy\crawler.py", line 325, in __init__
    super().__init__(settings)
  File "F:\software\python3.7\lib\site-packages\scrapy\crawler.py", line 197, in __init__
    self.spider_loader = self._get_spider_loader(settings)
  File "F:\software\python3.7\lib\site-packages\scrapy\crawler.py", line 191, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "F:\software\python3.7\lib\site-packages\scrapy\spiderloader.py", line 69, in from_settings
    return cls(settings)
  File "F:\software\python3.7\lib\site-packages\scrapy\spiderloader.py", line 24, in __init__
    self._load_all_spiders()
  File "F:\software\python3.7\lib\site-packages\scrapy\spiderloader.py", line 53, in _load_all_spiders
    for module in walk_modules(name):
  File "F:\software\python3.7\lib\site-packages\scrapy\utils\misc.py", line 92, in walk_modules
    submod = import_module(fullpath)
  File "F:\software\python3.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\weibo-search-master\weibo\spiders\search.py", line 15, in <module>
    class SearchSpider(scrapy.Spider):
  File "F:\weibo-search-master\weibo\spiders\search.py", line 37, in SearchSpider
    if util.str_to_time(start_date) > util.str_to_time(end_date):
  File "F:\weibo-search-master\weibo\utils\util.py", line 105, in str_to_time
    result = datetime.strptime(text, '%Y-%m-%d')
  File "F:\software\python3.7\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "F:\software\python3.7\lib\_strptime.py", line 544, in _strptime
    datetime_date(year, 1, 1).toordinal() + 1
ValueError: day is out of range for month

**Comment by dataabc** [comment]
有可能是settings.py的日期格式不对。
