### ISSUE TITLE
cookie无效或已过期

### ISSUE THREAD

**Issue by steven756284184** [dataabc/weibo-search#4]
如题。完全按照文档方法获取的cookie，setting.py中COOKIES_ENABLED的值改为True，但是无法使用。

**Comment by dataabc** [comment]
将COOKIES_ENABLED改成False应该就可以了

**Comment by steven756284184** [comment]
在改之前重新执行scrapy crawl search -s JOBDIR=crawls/search没有任何返回值并退出程序，改完之后仍然如此。。

**Comment by steven756284184** [comment]
重新git clone了一下，这次可以爬取了，但是每条微博的json下面都会报错
Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/weibo-search/venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/mac/PycharmProjects/weibo-search/venv/lib/python3.7/site-packages/scrapy/utils/defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/Users/mac/PycharmProjects/weibo-search/venv/lib/python3.7/site-packages/scrapy/pipelines/media.py", line 78, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "/Users/mac/PycharmProjects/weibo-search/venv/lib/python3.7/site-packages/scrapy/pipelines/media.py", line 78, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "/Users/mac/PycharmProjects/weibo-search/weibo/pipelines.py", line 48, in get_media_requests
    if len(item['weibo']['pics']) == 1:
TypeError: 'NoneType' object is not subscriptable
（抱歉，不知道为什么给错误信息套上``之后不能正常显示空格和换行）

**Comment by dataabc** [comment]
上面的命令行只有在cookie有效，COOKIES_ENABLED值为False时，按一次ctrl+c，下一次才可以恢复，否则就会没有反应退出。

下面的程序出错不知道是不是被限制才有的问题，看起来像是没有获取信息，但程序有试图获取pics才引起的。如果一直是这个问题，可以过一段时间再运行，也可以加大DOWNLOAD_DELAY。

**Comment by steven756284184** [comment]
换了多个时段一直不行。加大DOWNLOAD_DELAY也没用，并且是从第一页就开始报错。。我不太清楚怎么给scrapy设置断点debug。。不然可以提供更详细的信息

**Comment by steven756284184** [comment]
刚刚给`weibo/utils/pipelines.py`中`MyImagesPipeline`类的`get_media_requests`方法设置了断点（第48行），发现传给方法的参数`item`的值为`None`。如果不下载图片就不报错，大概是下载图片失败吧。。

**Comment by dataabc** [comment]
感谢反馈。

是否修改过其它代码？没想明白为什么csv输出图片却出错，感觉可以在get_media_requests中的条件语句加个item是否为None的判断，因为没有复现这个错误，不清楚是不是和具体关键词有关，你可以更换其它关键词看看

**Comment by steven756284184** [comment]
并未改其他代码，我换了两三个关键词都报错。加判断的话我觉得意义不大，因为目前观察是每逢图片必出错……由于没用过scrapy，我暂时没办法深究……如果有后续再来更新。

**Comment by steven756284184** [comment]
另外，请问“当前页面搜索结果为空”是正常的输出吗？

**Comment by dataabc** [comment]
> 另外，请问“当前页面搜索结果为空”是正常的输出吗？

是，说明没有搜索结果

**Comment by goxofy** [comment]
我也是，一直提示cookie无效或过期，但是可以确认cookied未过期

**Comment by BaLaLaLs** [comment]
自己电脑上运行不报错，放在服务器上报错。应该是微博反爬？

**Comment by dataabc** [comment]
@BaLaLaLs 
setting.py一样吗？如果不一样，可能是参数问题，如果一样我也不清楚。

**Comment by BaLaLaLs** [comment]
@dataabc 一样我现在本地也不行了
![Uploading image.png…]()

**Comment by dataabc** [comment]
@BaLaLaLs 

这是速度太快了，降低速度过一段时间在运行

**Comment by BaLaLaLs** [comment]
@dataabc 上面的截图setting有个地方不一样我开启了MongoPipeline，在我关闭后本地和服务器都可以了，不敢确定是不是MongoPipeline的问题

**Comment by dataabc** [comment]
@BaLaLaLs 
感谢反馈。和MongoPipeline没关系，可能是巧合。
