### ISSUE TITLE
运行报错，求助

### ISSUE THREAD

**Issue by monicawang724** [dataabc/weibo-search#406]
您好，我现在处于新手阶段，前几天利用您的代码爬取了一部分数据，但是今天输入命令之后，出现了报错，对于我来说解决起来比较苦难，所以想请您帮忙看一下，谢谢
 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\commands\crawl.py", line 30, in run
    self.crawler_process.start()
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\crawler.py", line 427, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\base.py", line 1318, in run
    self.mainLoop()
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\utils\reactor.py", line 58, in __call__
    return self._func(*self._a, **self._kw)
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\core\engine.py", line 175, in _next_request
    and self._next_request_from_scheduler() is not None
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\core\engine.py", line 211, in _next_request_from_scheduler
    request = self.slot.scheduler.next_request()
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\core\scheduler.py", line 277, in next_request
    request = self._dqpop()
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\core\scheduler.py", line 320, in _dqpop
    return self.dqs.pop()
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\pqueues.py", line 98, in pop
    m = q.pop()
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\squeues.py", line 72, in pop
    request = super().pop()
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\squeues.py", line 34, in pop
    s = super().pop()
  File "C:\Users\31435\AppData\Local\Programs\Python\Python311\Lib\site-packages\queuelib\queue.py", line 228, in pop
    self.f.seek(-size - self.SIZE_SIZE, os.SEEK_END)
builtins.OSError: [Errno 22] Invalid argument

**Comment by dataabc** [comment]
使用scrapy crawl search 看看。

**Comment by monicawang724** [comment]
> 使用命令行scrapy crawl search 运行看看。

这样可以了唉，非常感谢您
