### ISSUE TITLE
大佬，请问AttributeError: 'SelectReactor' object has no attribute '_handleSignals'这是怎么回事？

### ISSUE THREAD

**Issue by my4059** [dataabc/weibo-search#409]
Traceback (most recent call last):
  File "E:\Anaconda\envs\Machine-Learning\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Anaconda\envs\Machine-Learning\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\envs\Machine-Learning\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "E:\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\cmdline.py", line 158, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "E:\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\cmdline.py", line 111, in _run_print_help
    func(*a, **kw)
  File "E:\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\cmdline.py", line 166, in _run_command
    cmd.run(args, opts)
  File "E:\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\commands\crawl.py", line 30, in run
    self.crawler_process.start()
  File "E:\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\crawler.py", line 383, in start
    install_shutdown_handlers(self._signal_shutdown)
  File "E:\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\utils\ossignal.py", line 19, in install_shutdown_handlers
    reactor._handleSignals()
AttributeError: 'SelectReactor' object has no attribute '_handleSignals'

**Comment by dataabc** [comment]
可能是scrapy没有安装正确，我也不确定。

**Comment by Originszero** [comment]
scrapy库依赖于 twisted，可能二者版本不兼容导致，尝试着将 twisted改为: 22.10.0,
DOS窗口使用命令：pip uninstall -y && pip install twisted==22.10.0

**Comment by lijinghua22** [comment]
> `scrapy version == 2.11.0 python version == 3.8` scrapy库依赖于 twisted，可能二者不兼容导致，尝试着将 twisted改为: 22.10.0, DOS窗口使用命令：`pip uninstall -y && pip install twisted==22.10.0` 若 twisted 安装失败，可以到 [第三方库安装异常解决](https://www.lfd.uci.edu/~gohlke/pythonlibs/) Ctrl + F 搜索 Twisted 并找到与 python版本对应的 twisted 文件 <img alt="twisted安装异常" width="356" src="https://private-user-images.githubusercontent.com/111281323/290456576-6d819dee-f370-4297-8d8f-f67550a7cebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTk2MzUsIm5iZiI6MTcxMTM1OTMzNSwicGF0aCI6Ii8xMTEyODEzMjMvMjkwNDU2NTc2LTZkODE5ZGVlLWYzNzAtNDI5Ny04ZDhmLWY2NzU1MGE3Y2ViZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwOTM1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmQ0OTBkNzViMmEyODQ5NzJiZDhiNjU1MGNhNDYyN2Q0NzhjZjk0MGZkYjM3ZmYxZWY5Y2VjODViMWZjODU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NFPCuxviNr97kU_XDHHb9e7vJeI5nv901ZGo9rE48iE"> 一定要与系统的 位数对应，电脑是32位下载 32的那个，64位的同理

按照您的方法试了一遍,显示安装成功，但是还是报同样的错

**Comment by lijinghua22** [comment]
> 回溯（最近一次调用）：文件“E：\Anaconda\envs\Machine-Learning\lib\runpy.py”，第 193 行，_run_module_as_main“**main**”，mod_spec） 文件“E：\Anaconda\envs\Machine-Learning\lib\runpy.py”，第 85 行，_在 run_code exec（code， run_globals） 文件“E：\Anaconda\envs\Machine-Learning\Scripts\scrapy.exe__main__.py”，第 7 行，在文件“E：\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\cmdline.py”，第 158 行，在执行_run_print_help（解析器、_run_command、cmd、args、opts） 文件“E：\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\cmdline.py”，第 111 行，在 _run_print_help func（*a， **kw） 文件“E：\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\cmdline.py”，第 166 行，在 _run_command cmd.run（args， opts） 文件“E：\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\commands\crawl.py”，第 30 行，在运行 self.crawler_process.start（） 文件“E：\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\crawler.py”，第 383 行，在开始 install_shutdown_handlers（self._signal_shutdown） 文件“E：\Anaconda\envs\Machine-Learning\lib\site-packages\scrapy\utils\ossignal.py”，第 19 行，在 install_shutdown_handlers reactor._handleSignals（） AttributeError：“SelectReactor”对象没有属性“_handleSignals”

您好请问您最后解决了吗？
