### ISSUE TITLE
OSError: [WinError 87] 参数错误。

### ISSUE THREAD

**Issue by EdelweissGriffin** [dataabc/weibo-search#41]
在采集去年8月的数据的时候出现OSError: [WinError 87]这个错误。
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "d:\python37\lib\site-packages\scrapy\utils\python.py", line 347, in __next__
    return next(self.data)
  File "d:\python37\lib\site-packages\scrapy\utils\python.py", line 347, in __next__
    return next(self.data)
  File "d:\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "d:\python37\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "d:\python37\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "d:\python37\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "d:\python37\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\User\Desktop\coding\weibo-search-master\weibo\spiders\search.py", line 196, in parse_by_hour
    for weibo in self.parse_weibo(response):
  File "C:\Users\User\Desktop\coding\weibo-search-master\weibo\spiders\search.py", line 517, in parse_weibo
    print(weibo)
OSError: [WinError 87] 参数错误。

**Comment by EdelweissGriffin** [comment]
出现问题的微博都是这样的，前面正常的文字，后面一堆无法辨识字符
![QQ截图20201104183916](https://user-images.githubusercontent.com/71767727/98082652-328a8580-1ecd-11eb-9155-ab4b070b1835.jpg)
找到对应的原微博是这样的
![QQ截图20201104184228](https://user-images.githubusercontent.com/71767727/98082847-84cba680-1ecd-11eb-9295-13ebf9abdc87.jpg)

**Comment by dataabc** [comment]
应该是这些字符引起的，把weibo-search-master\weibo\spiders\search.py 中的print语句注释掉就可以了

**Comment by EdelweissGriffin** [comment]
> 感谢反馈。
> 
> 应该是这些字符引起的，把weibo-search-master\weibo\spiders\search.py 中的print语句注释掉就可以了。
> 
> 如果还有问题，欢迎继续讨论

感谢，解决了
