### ISSUE TITLE
不能正常运行了，很多字段有错误，很多报错

### ISSUE THREAD

**Issue by Junqiao77** [dataabc/weibo-search#421]
昨天都还是正常的可以爬取数据，今天早上就续行了，很多字段报错，下面只是其中一个，之前改了一些修复了一些，现在还有，求大佬解答
Traceback (most recent call last):
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\utils\defer.py", line 279, in iter_errback
    yield next(it)
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\utils\python.py", line 350, in __next__
    return next(self.data)
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\utils\python.py", line 350, in __next__
    return next(self.data)
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "C:\Users\80576\.conda\envs\Network_spider\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "C:\Users\\.conda\envs\Network_spider\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\python\WeiBo_Topic\weibo-search\weibo\spiders\search.py", line 109, in parse
    for weibo in self.parse_weibo(response):
  File "C:\python\WeiBo_Topic\weibo-search\weibo\spiders\search.py", line 519, in parse_weibo
    weibo['retweet_id'] = retweet['id']
  File "C:\Users\80576\.conda\envs\Network_spider\lib\site-packages\scrapy\item.py", line 79, in __getitem__
    return self._values[key]
KeyError: 'id'

**Comment by dataabc** [comment]
看起来是retweet没有id这个字段，我现在没法调试，不确定是什么原因。可能是被限制了，也有可能是修改代码的原因，比如可能之前修改过retweet相关的代码。

**Comment by Junqiao77** [comment]
> 看起来是retweet没有id这个字段，我现在没法调试，不确定是什么原因。可能是被限制了，也有可能是修改代码的原因，比如可能之前修改过retweet相关的代码。

我没有修改过retweet相关的代码，为了确保是否因为是我自己的修改造成了崩溃，我重新下载拉取了一次，仍然是无法运行的。

**Comment by dataabc** [comment]
可能是速度太快被暂时限制了吧，过几天再运行看看。

**Comment by ZOMBIE-E** [comment]
> > 看起来是retweet没有id这个字段，我现在没法调试，不确定是什么原因。可能是被限制了，也有可能是修改代码的原因，比如可能之前修改过retweet相关的代码。
> 
> 我没有修改过retweet相关的代码，为了确保是否因为是我自己的修改造成了崩溃，我重新下载拉取了一次，仍然是无法运行的。

请问您现在运行正常了吗，我也是这个问题

**Comment by Junqiao77** [comment]
> > > 看起来是retweet没有id这个字段，我现在没法调试，不确定是什么原因。可能是被限制了，也有可能是修改代码的原因，比如可能之前修改过retweet相关的代码。
> > 
> > 
> > 我没有修改过retweet相关的代码，为了确保是否因为是我自己的修改造成了崩溃，我重新下载拉取了一次，仍然是无法运行的。
> 
> 请问您现在运行正常了吗，我也是这个问题

没有，我还是那样的报错，无法正常运行。

**Comment by Junqiao77** [comment]
> > > 看起来是retweet没有id这个字段，我现在没法调试，不确定是什么原因。可能是被限制了，也有可能是修改代码的原因，比如可能之前修改过retweet相关的代码。
> > 
> > 
> > 我没有修改过retweet相关的代码，为了确保是否因为是我自己的修改造成了崩溃，我重新下载拉取了一次，仍然是无法运行的。
> 
> 请问您现在运行正常了吗，我也是这个问题

我已经可以正常运行了。
