### ISSUE TITLE
大佬，为什么我运行后报错呀，T T

### ISSUE THREAD

**Issue by lsw-777** [dataabc/weibo-search#422]
D:\Desktop\爬虫\weibo-search-master>scrapy crawl search
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\cmdline.py", line 160, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\crawler.py", line 357, in __init__
    super().__init__(settings)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\crawler.py", line 227, in __init__
    self.spider_loader = self._get_spider_loader(settings)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\crawler.py", line 221, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\spiderloader.py", line 79, in from_settings
    return cls(settings)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\spiderloader.py", line 34, in __init__
    self._load_all_spiders()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\spiderloader.py", line 63, in _load_all_spiders
    for module in walk_modules(name):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\utils\misc.py", line 106, in walk_modules
    submod = import_module(fullpath)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Desktop\爬虫\weibo-search-master\weibo\spiders\search.py", line 209
    """以小时和直辖市/省为单位筛选"""
       ^^^^^^^
SyntaxError: invalid syntax

**Comment by dataabc** [comment]
应该是你修改了search.py且代码格式不正确，根据错误提示修改就可以。

**Comment by dataabc** [comment]
有错误提示吗，或者您可以在网上搜索数据库相关问题。

**Comment by lsw-777** [comment]
没有错误提示，但就是有字段，没数据，语句什么的也是按照您的代码来修改的呢
<img width="960" alt="70e769dccb171f21d7ba55de237a44d" src="https://github.com/dataabc/weibo-search/assets/150653190/185bcfee-af07-4fe3-8427-311ca682d1df">
<img width="214" alt="c4e8134689c1f70a1d4732cda79aa43" src="https://github.com/dataabc/weibo-search/assets/150653190/33b97647-260c-437a-a378-f261491ce36f">

**Comment by dataabc** [comment]
修改过piplines.py吗？这里有写数据库的代码。

**Comment by lsw-777** [comment]
修改了，还是不行，哭了T T

**Comment by lsw-777** [comment]
大佬，还有的ip获取不到是什么原因呀

**Comment by dataabc** [comment]
ip可能是网页格式变了，我也不确定。数据库我猜可能是数据库配置原因，您在网上搜搜。
