### ISSUE TITLE
请问为什么更改setting的关键词之后不会生成新的结果文件

### ISSUE THREAD

**Issue by LOUISELUO2023** [dataabc/weibo-search#425]
运行第一次的时候生成了一个结果文件；后来更换了关键词并重启了Spyder，重新运行scrapy之后只会把结果输出到前一个结果文件里

**Comment by dataabc** [comment]
感谢反馈。因为默认命令行会按照进度文件继续执行之前的任务，如果更换关键词，需要把命令行crawls之后的部分换成其它名字，名字只有符合规范即可。

**Comment by LOUISELUO2023** [comment]
谢谢您的解答。我按照您的建议修改了命令，但是新的问题变成了微博网页里有无法识别的字符阻碍进程。GPT提供的修改方案没法解决问题，想请问一下您有没有可以补上去的代码？
下面是报错的内容：
`2023-11-22 10:31:08 [scrapy.core.scraper] ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=%23%E8%AF%B7%E5%A4%A7%E8%8B%B1%E5%8D%9A%E7%89%A9%E9%A6%86%E6%97%A0%E5%81%BF%E5%BD%92%E8%BF%98%E4%B8%AD%E5%9B%BD%E6%96%87%E7%89%A9#%20#%E9%80%83%E5%87%BA%E5%A4%A7%E8%8B%B1%E5%8D%9A%E7%89%A9%E9%A6%86%23&typeall=1&suball=1&timescope=custom:2023-08-27-0:2023-09-10-0> (referer: None)
Traceback (most recent call last):
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\utils\defer.py", line 257, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\utils\python.py", line 312, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\spidermiddlewares\referer.py", line 353, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Anaconda\Lib\site-packages\scrapy\core\spidermw.py", line 104, in process_sync
    for r in iterable:
  File "C:\Users\Administrator\weibo-search\weibo\spiders\search.py", line 109, in parse
    for weibo in self.parse_weibo(response):
  File "C:\Users\Administrator\weibo-search\weibo\spiders\search.py", line 538, in parse_weibo
    print(weibo)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f44d' in position 449: illegal multibyte sequence`

**Comment by 2OUMERTH** [comment]
> 运行第一次的时候生成了一个结果文件；后来更换了关键词并重启了Spyder，重新运行scrapy之后只会把结果输出到前一个结果文件里

这个我觉得有一个很简单的解决办法，你可以把第一次的运行结果改个名字就好了，这样你更改关键词，再scrapy会产生新的文件夹
