### ISSUE TITLE
想问这个报错的原因

### ISSUE THREAD

**Issue by qlgwwww** [dataabc/weibo-search#451]
修改了自己的cookie之后想测试运行一下，命令行scrapy crawl search运行后输出如下报错

**Comment by qlgwwww** [comment]
Traceback (most recent call last):
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\Scripts\scrapy.exe\__main__.py", line 4, in <module>
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\cmdline.py", line 9, in <module>
    from scrapy.commands import BaseRunSpiderCommand, ScrapyCommand, ScrapyHelpFormatter
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\commands\__init__.py", line 11, in <module>
    from scrapy.crawler import CrawlerProcess
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\crawler.py", line 27, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\core\engine.py", line 28, in <module>      
    from scrapy.core.downloader import Downloader
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\core\downloader\__init__.py", line 16, in <module>
    from scrapy.signalmanager import SignalManager
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\signalmanager.py", line 6, in <module>
    from scrapy.utils import signal as _signal
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\signal.py", line 20, in <module>
    from scrapy.utils.log import failure_to_exc_info
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\log.py", line 16, in <module>
    from scrapy.utils.versions import scrapy_components_versions
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\versions.py", line 13, in <module>
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\ssl.py", line 3, in <module>
    import OpenSSL._util as pyOpenSSLutil
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\SSL.py", line 10, in <module>
    from OpenSSL._util import (
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: 找不到指定的程序。
PS D:\desktop\课程文件\挑战杯\python爬虫\weibo-search-master> pip install twisted
Requirement already satisfied: twisted in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (23.10.0)
Requirement already satisfied: attrs>=21.3.0 in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from twisted) (23.1.0)
Requirement already satisfied: automat>=0.8.0 in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from twisted) (22.10.0)
Requirement already satisfied: hyperlink>=17.1.1 in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from twisted) (21.0.0)
Requirement already satisfied: incremental>=22.10.0 in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from twisted) (22.10.0)        
Requirement already satisfied: twisted-iocpsupport<2,>=1.0.2 in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from twisted) (1.0.4) 
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from twisted) (4.9.0)      
Requirement already satisfied: zope-interface>=5 in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from twisted) (6.1)
Requirement already satisfied: six in c:\users\qlgwwww\appdata\roaming\python\python39\site-packages (from automat>=0.8.0->twisted) (1.16.0)
Requirement already satisfied: idna>=2.5 in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from hyperlink>=17.1.1->twisted) (3.6)    
Requirement already satisfied: setuptools in c:\users\qlgwwww\appdata\local\programs\python\python39\lib\site-packages (from zope-interface>=5->twisted) (49.2.1)PS D:\desktop\课程文件\挑战杯\python爬虫\weibo-search-master> scrapy crawl search
Traceback (most recent call last):
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\Scripts\scrapy.exe\__main__.py", line 4, in <module>
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\cmdline.py", line 9, in <module>
    from scrapy.commands import BaseRunSpiderCommand, ScrapyCommand, ScrapyHelpFormatter
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\commands\__init__.py", line 11, in <module>
    from scrapy.crawler import CrawlerProcess
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\crawler.py", line 27, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\core\engine.py", line 28, in <module>
    from scrapy.core.downloader import Downloader
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\core\downloader\__init__.py", line 16, in <module>
    from scrapy.signalmanager import SignalManager
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\signalmanager.py", line 6, in <module>
    from scrapy.utils import signal as _signal
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\signal.py", line 20, in <module>
    from scrapy.utils.log import failure_to_exc_info
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\log.py", line 16, in <module>
    from scrapy.utils.versions import scrapy_components_versions
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\versions.py", line 13, in <module>
    from scrapy.utils.ssl import get_openssl_version
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\ssl.py", line 3, in <module>
    import OpenSSL._util as pyOpenSSLutil
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\SSL.py", line 10, in <module>
    from OpenSSL._util import (
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: 找不到指定的程序。

**Comment by qlgwwww** [comment]
Traceback (most recent call last):
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\Scripts\scrapy.exe\__main__.py", line 4, in <module>
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\cmdline.py", line 9, in <module>
    from scrapy.commands import BaseRunSpiderCommand, ScrapyCommand, ScrapyHelpFormatter
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\commands\__init__.py", line 11, in <module>     
    from scrapy.crawler import CrawlerProcess
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\crawler.py", line 27, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\core\engine.py", line 28, in <module>
    from scrapy.core.downloader import Downloader
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\core\downloader\__init__.py", line 16, in <module>
    from scrapy.signalmanager import SignalManager
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\signalmanager.py", line 6, in <module>
    from scrapy.utils import signal as _signal
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\signal.py", line 20, in <module>
    from scrapy.utils.log import failure_to_exc_info
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\log.py", line 16, in <module>
    from scrapy.utils.versions import scrapy_components_versions
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\versions.py", line 13, in <module>        
    from scrapy.utils.ssl import get_openssl_version
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\scrapy\utils\ssl.py", line 3, in <module>
    import OpenSSL._util as pyOpenSSLutil
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\SSL.py", line 10, in <module>
    from OpenSSL._util import (
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 
15, in <module>
    from cryptography.exceptions import InternalError
  File "C:\Users\qlgwwww\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\exceptions.py", line 9, in <module>       
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: 找不到指定的程序。

**Comment by qlgwwww** [comment]
我看了一下往期的Issues有看到各种各样的报错提问，但是这个_rust缺少DLL的情况没有发现诶，这是我哪里操作错了吗

**Comment by dataabc** [comment]
这个我也不知道，猜测可能和cryptography有关，你安装cryptography看看。

**Comment by leonieamor** [comment]
请问，我也遇到了同样的问题，重新安装了cryptography，还是显示上面的错误提示，请问有其他解决方法吗~ 谢谢
