### ISSUE TITLE
您好，我用您的代码运行后，报错如下，不知道该如何解决，跪求大佬帮忙

### ISSUE THREAD

**Issue by sully1218** [dataabc/weibo-search#461]
C:\Users\Administrator\Desktop\data\weibo-search>scrapy crawl search -s JOBDIR=crawls/search
Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "d:\anaconda\lib\site-packages\scrapy\cmdline.py", line 125, in execute
    settings = get_project_settings()
  File "d:\anaconda\lib\site-packages\scrapy\utils\project.py", line 71, in get_project_settings
    settings.setmodule(settings_module_path, priority="project")
  File "d:\anaconda\lib\site-packages\scrapy\settings\__init__.py", line 323, in setmodule
    module = import_module(module)
  File "d:\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'weibo.settings'; 'weibo' is not a package

**Comment by dataabc** [comment]
可能是scrapy安装不正确猜测，最好在官网安装。

**Comment by Liao-Ziqiang** [comment]
我也报了差不多的错误，重装scrapy、降版本都试过了，一直解决不了

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\ProgramData\anaconda3\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "C:\Users\25856\AppData\Roaming\Python\Python311\site-packages\scrapy\cmdline.py", line 114, in execute
    settings = get_project_settings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\25856\AppData\Roaming\Python\Python311\site-packages\scrapy\utils\project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "C:\Users\25856\AppData\Roaming\Python\Python311\site-packages\scrapy\settings\__init__.py", line 287, in setmodule
    module = import_module(module)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1135, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'weibo.settings'; 'weibo' is not a package

**Comment by dataabc** [comment]
@Liao-Ziqiang 可能是运行路径不对，应该在程序目录weibo-search下运行命令
```
scrapy crawl search
```

**Comment by Liao-Ziqiang** [comment]
@dataabc 目录没有错，就是在项目根目录，有scrapy.cfg的那个目录，配置应该也没错都用的原始的😭

**Comment by dataabc** [comment]
@Liao-Ziqiang 也可能和anaconda有关，最好单独安装python。
