### ISSUE TITLE
爬虫出现异常报错

### ISSUE THREAD

**Issue by kexinoh** [dataabc/weibo-search#468]
报错结果如下：
2024-04-14 19:19:00 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "D:\downloads\weibo-search-master\test.py", line 13, in <module>
    process.start()
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\crawler.py", line 429, in start
    reactor.run(installSignalHandlers=install_signal_handlers)  # blocking call
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\twisted\internet\base.py", line 1318, in run
    self.mainLoop()
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\twisted\internet\base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\twisted\internet\base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\utils\reactor.py", line 58, in __call__
    return self._func(*self._a, **self._kw)
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\core\engine.py", line 175, in _next_request
    and self._next_request_from_scheduler() is not None
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\core\engine.py", line 211, in _next_request_from_scheduler
    request = self.slot.scheduler.next_request()
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\core\scheduler.py", line 277, in next_request
    request = self._dqpop()
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\core\scheduler.py", line 320, in _dqpop
    return self.dqs.pop()
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\pqueues.py", line 98, in pop
    m = q.pop()
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\squeues.py", line 72, in pop
    request = super().pop()
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\scrapy\squeues.py", line 34, in pop
    s = super().pop()
  File "D:\downloads\weibo-search-master\venv\lib\site-packages\queuelib\queue.py", line 229, in pop
    self.f.seek(-size - self.SIZE_SIZE, os.SEEK_END)
builtins.OSError: [Errno 22] Invalid argument

**Comment by dataabc** [comment]
您参考下https://github.com/scrapy/scrapy/issues/845

**Comment by kexinoh** [comment]
我删除crawls文件夹之后，报错消失了，但是输出框中没有任何输出。

**Comment by dataabc** [comment]
直接运行 scrapy crawl search 看看。

**Comment by kexinoh** [comment]
在scrapy/core/engine.py里面插入                print("request",request)
可以看到如下输出：
request <GET https://s.weibo.com/weibo?q=%E6%AF%94%E7%89%B9%E5%B8%81&region=custom:34:1000&scope=ori&suball=1&timescope=custom:2024-04-11-0:2024-04-13-0>
request <GET https://s.weibo.com/weibo?q=%E6%AF%94%E7%89%B9%E5%B8%81&region=custom:11:1000&scope=ori&suball=1&timescope=custom:2024-04-11-0:2024-04-13-0>
request <GET https://s.weibo.com/weibo?q=%E6%AF%94%E7%89%B9%E5%B8%81&region=custom:50:1000&scope=ori&suball=1&timescope=custom:2024-04-11-0:2024-04-13-0>
request <GET https://s.weibo.com/weibo?q=%E6%AF%94%E7%89%B9%E5%B8%81&region=custom:35:1000&scope=ori&suball=1&timescope=custom:2024-04-11-0:2024-04-13-0>
request <GET https://s.weibo.com/weibo?q=%E6%AF%94%E7%89%B9%E5%B8%81&region=custom:62:1000&scope=ori&suball=1&timescope=custom:2024-04-11-0:2024-04-13-0>
request <GET https://s.weibo.com/weibo?q=%E6%AF%94%E7%89%B9%E5%B8%81&region=custom:44:1000&scope=ori&suball=1&timescope=custom:2024-04-11-0:2024-04-13-0>
同时crawls/search/requests.seen也会出现相应的值，但是结果文件没有出现相应关键词。

**Comment by dataabc** [comment]
是不是之前获取太多被暂时限制了？

**Comment by kexinoh** [comment]
我没有获取过很多，而且尝试把response.body输出转为html之后，显示如下情况，请问这种情况是合理的吗？
![image](https://github.com/dataabc/weibo-search/assets/91727108/449fc8a4-33f6-46c1-b3f0-f3ceeb4d3393)

**Comment by kexinoh** [comment]
现在可以正常运行了，解决方法是使用微博扫码验证登录。
一开始重新获取cookie没有效果，然后退出登录再扫码登录重新获取cookie解决。
