### ISSUE TITLE
请问一运行就会有这个错误

### ISSUE THREAD

**Issue by ArcherChloe** [dataabc/weibo-search#479]
C:\Users\33721\Desktop\weibo-search-master>scrapy crawl search -s JOBDIR=crawls/search
2024-05-18 12:51:09 [scrapy.core.scraper] ERROR: Spider error processing <GET https://s.weibo.com/weibo?q=%23%E6%8A%91%E9%83%81%E7%97%87%23&scope=ori&suball=1&timescope=custom:2024-03-14-0:2024-03-15-0&page=1> (referer: https://s.weibo.com/weibo?q=%23%E6%8A%91%E9%83%81%E7%97%87%23&scope=ori&suball=1&timescope=custom:2024-03-01-0:2024-05-02-0)
Traceback (most recent call last):
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\utils\defer.py", line 279, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\utils\python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\utils\python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\spidermiddlewares\referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\33721\AppData\Local\Programs\Python\Python312\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\33721\Desktop\weibo-search-master\weibo\spiders\search.py", line 153, in parse_by_day
    for weibo in self.parse_weibo(response):
  File "C:\Users\33721\Desktop\weibo-search-master\weibo\spiders\search.py", line 556, in parse_weibo
    print(weibo)
          ^^^^^
UnboundLocalError: cannot access local variable 'weibo' where it is not associated with a value
尝试改了一下但没有成功，请问一下怎么解决啊o(╥﹏╥)o

**Comment by dataabc** [comment]
感谢反馈。我现在不方便调试，您可以尝试修改search.py，把 avator = sel.xpath这行（大约在539行）及其之后的代码整体往后移动一个空格，看看有没有效果。

**Comment by scarydemon2** [comment]
> avator = sel.xpath

有效

**Comment by dataabc** [comment]
@Xxiaojinyi 是不是不小心把结果文件夹删除了？

**Comment by verazzz5** [comment]
请问在微博类型设置里面，能否筛选出无微博认证的普通微博用户？

**Comment by dataabc** [comment]
@verazzz5 这个我也不确定，程序模仿的是<https://s.weibo.com/>，如果这里可以应该就可以。
