### ISSUE TITLE
一运行就是重定向的问题，是cookie的问题吗，还有那个yield next(it)

### ISSUE THREAD

**Issue by wzz-hutao** [dataabc/weibo-search#524]
2024-12-28 12:25:08 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET https://passport.weibo.com/visitor/visitor?entry=miniblog
&a=enter&url=https%3A%2F%2Fs.weibo.com%2Fweibo%3Fq%3DAI%26scope%3Dori%26suball%3D1%26timescope%3Dcustom%3A2020-03-01-0%3A2020-12-15-0&domain=.weibo.co
m&sudaref=&ua=php-sso_sdk_client-0.6.29&_rand=1735359912.2968> from <GET https://s.weibo.com/weibo?q=AI&scope=ori&suball=1&timescope=custom:2020-03-01-0:2020-12-15-0>
2024-12-28 12:25:08 [scrapy_user_agents.middlewares] DEBUG: Assigned User-Agent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
2024-12-28 12:25:15 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2
Fs.weibo.com%2Fweibo%3Fq%3DAI%26scope%3Dori%26suball%3D1%26timescope%3Dcustom%3A2020-03-01-0%3A2020-12-15-0&domain=.weibo.com&sudaref=&ua=php-sso_sdk_client-0.6.29&_rand=1735359912.2968> (referer: None)
2024-12-28 12:25:15 [scrapy.core.scraper] ERROR: Spider error processing <GET https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=ht
tps%3A%2F%2Fs.weibo.com%2Fweibo%3Fq%3DAI%26scope%3Dori%26suball%3D1%26timescope%3Dcustom%3A2020-03-01-0%3A2020-12-15-0&domain=.weibo.com&sudaref=&ua=php-sso_sdk_client-0.6.29&_rand=1735359912.2968> (referer: None)
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\site-packages\scrapy\utils\defer.py", line 279, in iter_errback
    yield next(it)
          ^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\utils\python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\utils\python.py", line 350, in __next__
    return next(self.data)
           ^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "D:\Anaconda3\Lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "D:\Anaconda3\Lib\site-packages\scrapy\spidermiddlewares\referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "D:\Anaconda3\Lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "D:\Anaconda3\Lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "D:\pc\weibo-search-master\weibo-search-master\weibo-search\weibo\spiders\search.py", line 102, in parse
    is_empty = response.xpath(
               ^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\http\response\text.py", line 157, in xpath
    return self.selector.xpath(query, **kwargs)
           ^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\http\response\text.py", line 145, in selector
    self._cached_selector = Selector(self)
                            ^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\scrapy\selector\unified.py", line 97, in __init__
    super().__init__(text=text, type=st, **kwargs)
  File "D:\Anaconda3\Lib\site-packages\parsel\selector.py", line 496, in __init__
    root, type = _get_root_and_type_from_text(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\parsel\selector.py", line 377, in _get_root_and_type_from_text
    root = _get_root_from_text(text, type=type, **lxml_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\parsel\selector.py", line 329, in _get_root_from_text
    return create_root_node(text, _ctgroup[type]["_parser"], **lxml_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\parsel\selector.py", line 110, in create_root_node
    parser = parser_cls(recover=True, encoding=encoding, huge_tree=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\lxml\html\__init__.py", line 1887, in __init__
    super().__init__(**kwargs)
  File "src\\lxml\\parser.pxi", line 1806, in lxml.etree.HTMLParser.__init__
  File "src\\lxml\\parser.pxi", line 858, in lxml.etree._BaseParser.__init__
LookupError: unknown encoding: 'b'utf8''

**Comment by dataabc** [comment]
您登录<s.weibo.com>看看，猜测是被暂时限制了。

**Comment by wzz-hutao** [comment]
https://s.weibo.com/ 这个网站登录没问题，初学不知道问题在哪

**Comment by dataabc** [comment]
有可能cookie不正确，按照readme重新获取cookie看看。

**Comment by wzz-hutao** [comment]
cookie是按照readme来的，我还用了别人的cookie试了，而且的我普通的xpath，随便一个简单的爬虫，都让我什么登录，给我看傻了

**Comment by wzz-hutao** [comment]
url = 'https://s.weibo.com/weibo?q=AI%E6%8D%A2%E8%84%B8&Refer=index'
response = requests.get(url,headers=headers)
print(response.text)
给我返回的是java内容，而不是html类似的内容

**Comment by dataabc** [comment]
可能是账号原因，如果方便，换个账号看看。

**Comment by 2871858184** [comment]
遇到了一样的问题。。response is  <200 https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fs.weibo.com%2Fweibo%3Fq%3D%25E5%258C%2597%25E4%25BA%25AC%2520%25E5%25AE%259C%25E5%25B1%2585%25E5%259F%258E%25E5%25B8%2582%26scope%3Dori%26suball%3D1%26timescope%3Dcustom%3A2021-01-27-0%3A2022-01-27-17%26display%3D0%26retcode%3D6102&domain=.weibo.com&sudaref=&ua=php-sso_sdk_client-0.6.29&_rand=1735752643.2866>。是不是微博改了什么

**Comment by dataabc** [comment]
@cloudy-sfu 暂时没有必要加到README里，一是有打广告之嫌，二是cookie太过隐私，三是第三方的东西不是我们能控制的，万一出了安全隐患，后果不堪设想。
