### ISSUE TITLE
需要爬取分别几百个关键词个内容，导致CPU、内存占用率高，MYSQL也挂掉了

### ISSUE THREAD

**Issue by WhoIAmm** [dataabc/weibo-search#56]
如题所述，有什么办法处理吗？是因为并行了还是怎么样，导致CPU内存的占用高，mysql也宕，谢谢！

**Comment by WhoIAmm** [comment]
2020-12-29 17:02:39 [scrapy.core.scraper] ERROR: Error processing {'weibo': {'created_at': '2020-12-13 16:40',
 'id': '4581712418052056',
 'text': '#金义东轨道首列客车出镜首秀##金华##金义东城际轻轨试运行时间公布##义乌商贸城#2金华·东阳木雕博物馆#东阳横店影视城#2金华·东阳横店电影城  '
         '以后外地朋友们到金义都市新区（菜鸟电子科技驿站）、未来金华义乌国际机场（孝顺）、义乌现飞机场、保税区、义乌国际商贸城、东阳横店电影城和现飞机场十分轻松愉快，下了高铁就可以直接到达目的地！浙江等地到金华站、金华南站、金义都高铁站由金义转换高铁到杭州东站、杭州南站（萧山站）坐7号地铁可直达萧山国际机场。去其他城市也十分便捷，零距离空间更换，现高铁到上海一个半小时，杭州43分钟、萧山39分钟，义乌15分钟，悬磁浮列车运行上来，上海至杭州20分钟，杭到金义都是10至20分钟的车程，杭州宁波大湾区城市群半小时，上海长三角城市群一小时生活圈，打造智慧城市全网无人驾驶覆盖范围，建议看看30年的浙江交通展示，非常兴奋\U0001f970。釆购追星\U0001f929观光旅游为一体，即方便游人商户，又方便市民低碳环保安全出行，访友走亲，办公上班，金义东一小时生活圈巳建好。待新能源汽车小镇、永康科技五金城、磐安药材市场、浦江水晶城吊灯（接上海7号地铁）、兰溪纺织水泥水果产业、兰溪诸葛八卦村、武义温泉、江南九寨沟牛头山、田庐民宿、金华建德千岛湖高铁上黄山旅游、金义甬（宁波舟山航运）、金台（台州）等地连好，城际铁路开通运营，零距离交换低碳环保行走！想致富，先修路，北方都在等上面投资项目注入活力启动，南方都在挖空心思找资源开发，先做起来再说！ '
         '收起全文d'}, 'keyword': '上海 低碳', 'city': '上海', 'search_keyword': '低碳'}
Traceback (most recent call last):
  File "/root/weibo_search/weibo-search/weibo/pipelines.py", line 189, in process_item
    self.cursor.execute(sql, tuple(data.values()))
  File "/root/anaconda3/envs/weibo_search/lib/python3.6/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/root/anaconda3/envs/weibo_search/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/root/anaconda3/envs/weibo_search/lib/python3.6/site-packages/pymysql/connections.py", line 504, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/root/anaconda3/envs/weibo_search/lib/python3.6/site-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/weibo_search/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/anaconda3/envs/weibo_search/lib/python3.6/site-packages/scrapy/utils/defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/root/weibo_search/weibo-search/weibo/pipelines.py", line 193, in process_item
    self.db.rollback()
  File "/root/anaconda3/envs/weibo_search/lib/python3.6/site-packages/pymysql/connections.py", line 431, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/root/anaconda3/envs/weibo_search/lib/python3.6/site-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
pymysql.err.InterfaceError: (0, '')

**Comment by dataabc** [comment]
感谢反馈。

可以参考[Scrapy settings](https://docs.scrapy.org/en/latest/topics/settings.html)的CONCURRENT_REQUESTS，不知道是否有帮助。如果还有问题，欢迎继续讨论。
