### ISSUE TITLE
大佬可以看一下吗

### ISSUE THREAD

**Issue by piaomiaoaxin** [dataabc/weibo-search#62]
AttributeError: 'SearchSpider' object has no attribute 'state'
这个是啥问题

**Comment by dataabc** [comment]
我也没遇到过这个问题，你是不是修改代码了？参考<https://stackoverflow.com/questions/27050449/crawlspider-derived-object-das-no-attribute-state>

**Comment by piaomiaoaxin** [comment]
没有呀，刚开始好好的，爬了85条停了，再运行就报这个错误了，是不是python，scrapy版本问题

**Comment by piaomiaoaxin** [comment]
又试了一下，爬了几条又报这个错
2021-03-01 21:39:37 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method SpiderState.spider_closed of <scrapy.extensions.spiderstate.SpiderState object at 0x7f8bbb37f9e8>>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/scrapy/utils/defer.py", line 164, in maybeDeferred_coro
    result = f(*args, **kw)
  File "/usr/local/python3/lib/python3.5/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/local/python3/lib/python3.5/site-packages/scrapy/extensions/spiderstate.py", line 29, in spider_closed
    pickle.dump(spider.state, f, protocol=4)
AttributeError: 'SearchSpider' object has no attribute 'state'

**Comment by dataabc** [comment]
可以运行
```
scrapy crawl search
```
只是这样就没进度了，猜测上面应该是进度保存不正确导致的。

**Comment by piaomiaoaxin** [comment]
这个可以了  谢谢你！
