### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by WXONE** [dataabc/weibo-search#65]
Traceback (most recent call last):
  File "D:/weibo/spiders/search.py", line 37, in <module>
    class SearchSpider(scrapy.Spider):
  File "D:/weibo/spiders/search.py", line 43, in SearchSpider
    if not os.path.isabs(keyword_list):
  File "D:\anaconda3\lib\ntpath.py", line 63, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType
报错内容如上，请问如何解决

**Comment by dataabc** [comment]
keyword_list应该是关键词列表或文件路径，可能是这个参数错了，改成list的形式就可以了。
