### ISSUE TITLE
无法运行~~

### ISSUE THREAD

**Issue by mvuvu** [dataabc/weibo-search#82]
使用Windows系统运行$ scrapy crawl search -s JOBDIR=crawls/search时出现以下错误，麻烦大佬看一看，谢谢。

F:\Code\WeiboSearch\weibo-search>scrapy crawl search
Traceback (most recent call last):
  File "e:\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "e:\anaconda3\lib\site-packages\scrapy\cmdline.py", line 114, in execute
    settings = get_project_settings()
  File "e:\anaconda3\lib\site-packages\scrapy\utils\project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "e:\anaconda3\lib\site-packages\scrapy\settings\__init__.py", line 287, in setmodule
    module = import_module(module)
  File "e:\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'weibo.settings'; 'weibo' is not a package

**Comment by dataabc** [comment]
参考<https://blog.csdn.net/lllunaticer/article/details/83180970>

**Comment by hanwenbo** [comment]
买个mac吧 或者用虚拟机  windows有难度

**Comment by mvuvu** [comment]
> 参考https://blog.csdn.net/lllunaticer/article/details/83180970

谢谢大佬回复，请问这个可以加代理IP吗，不加的话被封IP的风险高吗？

**Comment by dataabc** [comment]
本程序不提供多ip支持，你可以参考网上的方法，速度不快的话被封问题不大，建议使用不常用的账号

**Comment by mvuvu** [comment]
> 本程序不提供多ip支持，你可以参考网上的方法，速度不快的话被封问题不大，建议使用不常用的账号

好的，多谢!
