### ISSUE TITLE
之前可以运行的，突然不行了

### ISSUE THREAD

**Issue by Hanzhangchen2021** [dataabc/weibo-search#90]
2021-07-15 08:27:21 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method SpiderState.spider_opened of <scrapy.extensions.spiderstate.SpiderState object at 0x7fb5be41b7b8>>
Traceback (most recent call last):
  File "/Users/chz/opt/anaconda3/envs/py36/lib/python3.6/site-packages/scrapy/utils/defer.py", line 157, in maybeDeferred_coro
    result = f(*args, **kw)
  File "/Users/chz/opt/anaconda3/envs/py36/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/Users/chz/opt/anaconda3/envs/py36/lib/python3.6/site-packages/scrapy/extensions/spiderstate.py", line 34, in spider_opened
    spider.state = pickle.load(f)
EOFError: Ran out of input
Unhandled Error
Traceback (most recent call last):
  File "/Users/chz/opt/anaconda3/envs/py36/lib/python3.6/site-packages/scrapy/commands/crawl.py", line 27, in run
    self.crawler_process.start()
  File "/Users/chz/opt/anaconda3/envs/py36/lib/python3.6/site-packages/scrapy/crawler.py", line 327, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/Users/chz/opt/anaconda3/envs/py36/lib/python3.6/site-packages/twisted/internet/base.py", line 1423, in run
    self.mainLoop()
  File "/Users/chz/opt/anaconda3/envs/py36/lib/python3.6/site-packages/twisted/internet/base.py", line 1433, in mainLoop
    reactorBaseSelf.runUntilCurrent()

**Comment by dataabc** [comment]
是否修改过代码？

**Comment by Hanzhangchen2021** [comment]
您好，没有修改过代码，就突然某一天不行了

**Comment by dataabc** [comment]
执行
```
scrapy crawl search
```
有错吗

**Comment by Hanzhangchen2021** [comment]
无比感谢！我之前执行的是scrapy crawl search -s JOBDIR=crawls/search 现在变成scrapy crawl search就可以了！！！太感谢您了

**Comment by dataabc** [comment]
客气了。第一个命令在使用一次ctr+c会保存进度，现在的命令无法保存进度，不知道是不是进度文件有问题才出错。如果你想保存进度，可以使用
```
scrapy crawl search -s JOBDIR=crawls/search1
```
