### ISSUE TITLE
运行 scrapy crawl search报错

### ISSUE THREAD

**Issue by snnuzyxc** [dataabc/weibo-search#95]
Traceback (most recent call last):
  File "d:\program files (x86)\python3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\python3.7\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "d:\program files (x86)\python3.7\lib\site-packages\scrapy\cmdline.py", line 114, in execute
    settings = get_project_settings()
  File "d:\program files (x86)\python3.7\lib\site-packages\scrapy\utils\project.py", line 63, in get_project_settings
    init_env(project)
  File "d:\program files (x86)\python3.7\lib\site-packages\scrapy\utils\conf.py", line 86, in init_env
    cfg = get_config()
  File "d:\program files (x86)\python3.7\lib\site-packages\scrapy\utils\conf.py", line 100, in get_config
    cfg.read(sources)
  File "d:\program files (x86)\python3.7\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "d:\program files (x86)\python3.7\lib\configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'D:\\weibo-search-master\\weibo-search-master\\scrapy.cfg', line: 1
'scrapy crawl search -s JOBDIR=crawls/search# Automatically created by: scrapy startproject\n'

**Comment by snnuzyxc** [comment]
D:\weibo-search-master\weibo-search-master> scrapy crawl search

会是运行的目录错了吗

**Comment by dataabc** [comment]
不是目录的错，参考下<https://blog.csdn.net/ligu2622/article/details/79608451>。

**Comment by snnuzyxc** [comment]
试了，还是不行，依旧是这个错位，是只能用其他方案里的代码吗，notepad++改后还是失败，一样的错误

**Comment by dataabc** [comment]
应该就是编码的问题，网上的解决方案都类似的，或者如果运行其它程序也出错，可能就是scrapy没装好，重新安装

**Comment by snnuzyxc** [comment]
嗯嗯，好的，我把scrapy重新安装试试
